image: justanemo/pdv-buildcontainer:main

stages:
    - build

variables:
    LC_ALL: 'en_US.UTF-8'
    DEBIAN_FRONTEND: 'noninteractive'

build-newifid2:
    stage: build
    before_script:
        - rm -rf toolchain
        - ln -sf /opt/padavan-ng/toolchain toolchain
    script:
        - cd trunk
        - cp configs/templates/newifi/newifi-d2.config .config
        - ./build_firmware.sh
        - cd ..
    artifacts:
        paths:
            - trunk/images/
    
